### ISSUE TITLE
SIC Code

### ISSUE THREAD

**Issue by SScottRoth** [janlukasschroeder/sec-api#10]
Jan,

I see you have some web based apps that allow you to look up companies and obtain their SIC code.   http://mapping-api.herokuapp.com/sic/3711  And I see the streaming version allows you to pull the SIC code back but the query based one does not have it as a parameter.  Any chance you are going to add it to your https://sec-api.io/ api.

Regards,

Scott Roth

**Comment by janlukasschroeder** [comment]
@SScottRoth are you suggesting to add the SIC code of a ticker symbol to a filing?

**Comment by SScottRoth** [comment]
Hi Jan,

I apologize - its been a while. I think I asked this question before I was more conversant with python.  Let me review your API and see if I have any further questions.  thank you.

Scott Roth
