### ISSUE TITLE
Authentication Issues (You are not subscribed error)

### ISSUE THREAD

**Issue by arabnizam** [janlukasschroeder/sec-api#14]
i have 2 API keys to access the sec-api data and try get the data with those keys but every time i am getting the same below error

const api = require('sec-api')('My_Key');
api.on('filing', filing => console.log(filing));

"You are not subscribed. Please subscribe to access the live stream. Visit https://sec-api.io or send an email to support@sec-api.io"

**Comment by janlukasschroeder** [comment]
@arabnizam you require an active subscription to use the stream API. hope this helps.

**Comment by armisticeTDantas** [comment]
Does this mean the trial does not extend to the stream api?
