### ISSUE TITLE
No XBRL Data Available

### ISSUE THREAD

**Issue by bbkrr** [janlukasschroeder/sec-api#18]
CIK: 0000355379

Using sec-api we get a message `'No XBRL data available for this filing. XBRL was made mandatory in 2009. You can find more details here: https://www.sec.gov/page/osdhistoryandrulemaking'`

But from companyfacts we can actually get the data of this CIK.
Link to companyfacts: `https://data.sec.gov/api/xbrl/companyfacts/CIK0000355379.json`

So, why is sec-api not able to extract data of this CIK, is it not XBRL ?

**Comment by janlukasschroeder** [comment]
All data is available for CIK 0000355379.

Using the XBRL-JSON API and the most recent 10-Q of 0000355379, the GET request would look like this:

```
https://api.sec-api.io/xbrl-to-json?
token=YOUR_API_KEY&
htm-url=https://www.sec.gov/Archives/edgar/data/355379/000155837021015733/mdwt-20210930x10q.htm
```

**Comment by bbkrr** [comment]
@janlukasschroeder 

Actually I was looking for the 10K data which is available in Edgar database but sec-api threw an error.

url: https://www.sec.gov/Archives/edgar/data/355379/000155837021003013/mdwt-20201231x10k.htm

**Comment by janlukasschroeder** [comment]
@bbkrr great pick up! thanks for clarifying. you found a very rare edge case that the converter didn't pick up. the issue is resolved and the XBRL data is returned as expected:

```
https://api.sec-api.io/xbrl-to-json?
token=YOUR_API_KEY&
htm-url=https://www.sec.gov/Archives/edgar/data/355379/000155837021003013/mdwt-20201231x10k.htm
```

**Comment by bbkrr** [comment]
@janlukasschroeder 

Thank you for the quick change. Indeed we get the data from url='https://www.sec.gov/Archives/edgar/data/355379/000155837021003013/mdwt-20201231x10k.htm'. 

But it should also give the result for url='https://www.sec.gov/Archives/edgar/data/0000355379/000155837021003013/mdwt-20201231x10k.htm'.

Which is same CIK but only added with zeros at the beginning. CIK = 355379 or CIK = 0000355379.

I checked this with other companies using sec-api and it works for all the other companies even if there are zeros in the beginning but it does not work for this company.
