### ISSUE TITLE
additional features

### ISSUE THREAD

**Issue by HedgeShot** [janlukasschroeder/sec-api#2]
Hi,

Thanks a lot for this tool, it is great. 
Do you plan on adding a way to "search" for latest filings for example by CIK number? It will avoid missing some filings if the user server goes down (or the heroku instance).

**Comment by janlukasschroeder** [comment]
@HedgeShot great idea! 

at the moment searching historical filings is only possible by using my front-end [newsfilter.io ](https://newsfilter.io/?filter=c90ddef5-a4d0-4f07-b834-89046370fb2a). I'll work on this over the weekend and might be able to release "search" early next week.

**Comment by janlukasschroeder** [comment]
@HedgeShot 

I managed to develop a first version of a "search" function for historical filings. You can search by CIK, form type, filing date, and company name (see example below). I'll add "search by ticker" soon.

My system is still indexing historical filings - 2014 to 2018 is done. 2019 and before 2014 is in progress.

API: https://api.sec-api.io
Supported HTTP methods: `POST` (I'll add `GET` support soon)

# Examples

## 10Qs of Apple in 2016

Get all filings of Apple (CIK: `320193`), filed between 2016-01-01 and 2016-12-31.

### Request
`POST https://api.sec-api.io`
Payload: 
```json
{
    "query": {
        "query_string": {
            "query": "cik:320193 AND filedAt:{2016-01-01 TO 2016-12-31}"
        }
    },
    "from": "0",
    "size": "10",
    "sort": [
        {
            "filedAt": {
                "order": "desc"
            }
        }
    ]
}
```
   
### Response
```json
{
    "hits": {
        "total": 118,
        "hits": [
            {
                "_index": "filings",
                "_type": "_doc",
                "_id": "bcfffc0140b155ac6cb2ad22dd6c751e",
                "_score": null,
                "_source": {
                    "cik": "320193",
                    "ticker": "AAPL",
                    "companyName": "APPLE INC",
                    "formType": "4",
                    "filedAt": "2016-12-29",
                    "linkToTxt": "https://www.sec.gov/Archives/edgar/data/320193/0001628280-16-022242.txt",
                    "linkToHtml": "https://www.sec.gov/Archives/edgar/data/320193/0001628280-16-022242-index.htm",
                    "id": "bcfffc0140b155ac6cb2ad22dd6c751e"
                },
                "sort": [
                    1482969600000
                ]
            },
            {
                "_index": "filings",
                "_type": "_doc",
                "_id": "46f80b6f2016fee7c2d754740989b8c7",
                "_score": null,
                "_source": {
                    "cik": "320193",
                    "ticker": "AAPL",
                    "companyName": "APPLE INC",
                    "formType": "4",
                    "filedAt": "2016-12-19",
                    "linkToTxt": "https://www.sec.gov/Archives/edgar/data/320193/0001628280-16-022104.txt",
                    "linkToHtml": "https://www.sec.gov/Archives/edgar/data/320193/0001628280-16-022104-index.htm",
                    "id": "46f80b6f2016fee7c2d754740989b8c7"
                },
                "sort": [
                    1482105600000
                ]
            }
  ]
}
}
```

**Comment by HedgeShot** [comment]
Thanks for the update and the great work!
How long do you plan to keep your server up? and will you switch to paid plan to keep it going?

cheers

**Comment by janlukasschroeder** [comment]
@HedgeShot the API will be running 24/7 and for the next 3 months I'll provide free access. I'm more than happy to give you free life-time access if you keep on sending through feedback and your thoughts - I would really appreciate this!

**Comment by HedgeShot** [comment]
@janlukasschroeder thx, I am happy to give you feedback but i will also be happy to pay should I use the service! I haven't had time yet to test the new feature but will surely look into it soon.
