### ISSUE TITLE
Type of amendments

### ISSUE THREAD

**Issue by bbkrr** [janlukasschroeder/sec-api#20]
I encountered an issue while fetching 10-K/A form. It seems we don't have any response to check if the fetched amendment form is of 'Amendment No. 1' or 'Amendment No. 2'. 

I used Full-Text Search API to check the types of amendment but it looks like some of the files contain both of the string 'Amendment No. 1' and 'Amendment No. 2', which makes it harder to differentiate the types.

**Comment by janlukasschroeder** [comment]
@bbkrr did you try using the "CoverPage.AmendmentDescription" parameter returned by the XBRL-to-JSON API? 

For example, "CoverPage.AmendmentDescription" is set to "Amendment\nNo. 1" for
 https://www.sec.gov/Archives/edgar/data/1397016/000149315222003102/form10-ka.htm

**Comment by bbkrr** [comment]
> @bbkrr did you try using the "CoverPage.AmendmentDescription" parameter returned by the XBRL-to-JSON API?
> 
> For example, "CoverPage.AmendmentDescription" is set to "Amendment\nNo. 1" for https://www.sec.gov/Archives/edgar/data/1397016/000149315222003102/form10-ka.htm

Hi @janlukasschroeder 

In one of the cik there is no `CoverPage`, is it a bug ?

link: https://www.sec.gov/ix?doc=/Archives/edgar/data/898174/000089817421000006/rga-20201231.htm
