### ISSUE TITLE
Multiple items in one Extraction

### ISSUE THREAD

**Issue by sash236** [janlukasschroeder/sec-api#23]
The example below states:
"section_text = extractorApi.get_section(filing_url, "1A", "text")"
https://sec-api.io/docs/sec-filings-item-extraction-api-python-example

How can be add multiple sections in one pull?
Also pulling "1" will not include "1A". In place of "1" using a variable and doing a for loop does not work either!

Is there a way efficiently pull a range of items?

**Comment by janlukasschroeder** [comment]
@sash236 The Extractor API supports one item extraction per API call. Try using a loop to extract multiple items per filing URL.

**Comment by sash236** [comment]
I tried for loop in python. Also tried passing item as an integer and string. It did not work.
