### ISSUE TITLE
ExtractorApi returns "undefined"

### ISSUE THREAD

**Issue by sash236** [janlukasschroeder/sec-api#25]
ExtractorApi returns "undefined" for URLs of the format:
https://www.sec.gov/ix?doc=/Archives/edgar/data/.......

Example:
url = 'https://www.sec.gov/ix?doc=/Archives/edgar/data/0000004281/000000428120000038/form10k4q19.htm'

extractorApi.get_section( url, "1", "text")

Returned: "undefined"

sec-api does not work for newver  SEC format?

**Comment by janlukasschroeder** [comment]
@sash236 The Extractor API works are usual and is 100% operational. We also checked your URL and we successful receive item 1 in text format. You might have run out of free API requests. Please double check.

**Comment by sash236** [comment]
@janlukasschroeder  I seriously think that it was a mistake to close this since it was throwing "Undefined" and not an "API error". If the issue is license then it throws "API error".  

If it were license, the code typically crashes.

Another reason for this conclusion was the undefined came for the 1st and 3rd URL that was passed. But the 2nd URL worked fine. Only difference in the URL is the format as stated on the issue.

If you were able to pull Item 1 using the same URL, then there might be a reliability issue.

**For what issue the sec-api throws "undefined"?**

**Comment by finfly100** [comment]
Unsubscribe
