### ISSUE TITLE
Problem to test api

### ISSUE THREAD

**Issue by toshuomj** [janlukasschroeder/sec-api#3]
I followed the steps to install sec-api in command-line

> Command Line
> In your command line, type
> 
> npm install sec-api -g to install the package
> 
> sec-api YOUR_API_KEY to connect to the stream. Replace YOUR_API_KEY with the API key provided on sec-api.io
> 
> Done! You will filings printed in your command line as soon as they are published on SEC EDGAR.

When I launch the command sec-apy (MY API KEY), after a few minutes I receive this message "Socket connected to https://socket.sec-api.io/all-filings"

If I connect to that link, the following page opens. (1)
![1](https://user-images.githubusercontent.com/32103764/58971943-c1690f00-87bc-11e9-9c25-02434843f520.png)

But if I connect to https://socket.sec-api.io/ the following page opens. (2)
![2](https://user-images.githubusercontent.com/32103764/58971958-c8901d00-87bc-11e9-946c-2d50ec5d4810.png)

I've been testing for a few days, and no "filling" has ever been shown per terminal (from the website either).
I have also followed the steps for node.js, and the result has also been the same as for "command-line".
After a few more minutes, if we update the page, the result is this. And the command keeps running.
![3](https://user-images.githubusercontent.com/32103764/58971971-cc23a400-87bc-11e9-8bfa-2cbf6e7c2711.png)

In addition, we check on the sec.gov website for latest filings and actually there is some publications so the api should list them.

Is there something I am doing wrong or the api is currently broken ?

**Comment by janlukasschroeder** [comment]
@toshuomj thanks for post! I fixed a bug two days ago and everything should work fine again. Try to type `sec-api YOUR_API_KEY` in your command line and you should see filings again. Let me know if everything works as expected.

Typing `https://socket.sec-api.io/all-filings` into your browser won't work. this URL can only be used by a socket.io client.

**Comment by toshuomj** [comment]
@janlukasschroeder Thanks for your answer. I've been running the command for about an hour and nothing is shown on the screen (only "Socket connected to https://socket.sec-api.io/all-filings"). And on SEC.gov's "Latest Filings Received and Processed at the SEC" page they are loaded almost every minute.
Maybe I should configure something else besides installing the package with the command "npm install sec-api -g"?

**Comment by janlukasschroeder** [comment]
I just checked the client again - it turned out that my client was missing a `print` method.

Type in 
- `npm update sec-api -g`
- `sec-api YOUR_API_KEY` 
- Works now :)

**Comment by toshuomj** [comment]
Yes thank you, now it has worked!
