### ISSUE TITLE
Websocket Delays

### ISSUE THREAD

**Issue by mcg88** [janlukasschroeder/sec-api#32]
id 7060c2f223db6f67ad1e546e1187a405

This appeared on the secapi ws at "time": "2023-03-23T10:14:26.268414"
However, this filing was publicly available much earlier. I'm showing benzinga had it at 06:05:37 EST and bloomberg had it at 06:05:19 so looks like there was a lag of about 9 minutes from when secapi received and processed it

**Comment by FreeGoldRush** [comment]
Are you still seeing this issue?  Is the websocket working for you this morning?
