### ISSUE TITLE
Simplify search query

### ISSUE THREAD

**Issue by volgin** [janlukasschroeder/sec-api#4]
What is the value of having 'query' inside 'query_string' inside 'query'?

```
"query": {
        "query_string": {
            "query": "cik:320193 AND filedAt:{2016-01-01 TO 2016-12-31} AND formType:\"10-Q\""
        }
    },
```
Wouldn't simply 'query' be enough? That will certainly simplify the use of the API.

**Comment by janlukasschroeder** [comment]
> What is the value of having 'query' inside 'query_string' inside 'query'?

My API allows more complex queries than Lucene query strings, ie `query_string` is only one of many supported operators (still to be documented). For example:

```
{
    "query": {
        "match_phrase" : {
            "companyName" : "Apple"
        }
    }
}
```

**Comment by volgin** [comment]
OK, I will wait for more documentation :)
