### ISSUE TITLE
No data coming down the stream

### ISSUE THREAD

**Issue by FreeGoldRush** [janlukasschroeder/sec-api#40]
I followed the instructions for receiving streaming data and created:

const { streamApi } = require('sec-api');
streamApi.connect('YOUR_API_KEY');
streamApi.on('filing', (filing) => console.log(filing));

It connects using my API_KEY and returns "Socket connected to https://api.sec-api.io:3334/all-filings" nothing else is printed on stdout even though I see new filings appearing at the SEC website.  Does anyone have this working?

Thank you!

**Comment by FreeGoldRush** [comment]
This was closed as "completed" but still not seeing data coming down the stream. Any assistance would be appreciated.

**Comment by janlukasschroeder** [comment]
@FreeGoldRush if you can please contact our support at support@sec-api.io, that would be greatly appreciated
