### ISSUE TITLE
Feedback on S-1 / 424 Endpoint

### ISSUE THREAD

**Issue by mcg88** [janlukasschroeder/sec-api#42]
Hi Jan,

Just noticed and played around a little bit with the new endpoints. I had a couple thoughts that would be very useful to me.

1) Possible to include 424b5 filings?
2) In the endpoint response, return the type of securities being registered. Here is an example from KAVL S-1
![image](https://github.com/janlukasschroeder/sec-api/assets/4948638/8da4fcf0-9f11-49da-83be-600e86890a83)

3) Include the cover text / or a way to extract it? There is very useful information here about the terms of the offering. The green text box is what I'm thinking.
![image](https://github.com/janlukasschroeder/sec-api/assets/4948638/5b5f1ba7-2fe1-4f99-b4dd-29629927bacf)

Thanks for your consideration! @janlukasschroeder

**Comment by janlukasschroeder** [comment]
Great idea! New feature added: 
https://sec-api.io/docs/form-s1-424b4-data-search-api
