### ISSUE TITLE
PdfGeneratorApi Cache Miss 202

### ISSUE THREAD

**Issue by lilly-lumosity** [janlukasschroeder/sec-api#44]
Hello,

Thank you for the great package!!

I am running into an issue with the PdfGeneratorApi. I am attempting to download EX-99 files as PDFs. When I use `https://api.sec-api.io/filing-reader` endpoint I get a 202. Using the `pdfGeneratorApi.get_pdf(url_pdf_file)` I also get a 202, with the message  "API error: 202 - {"message":"Cache miss: PDF generation started. Retry in 5 seconds."}". 
No matter how may times I retry or how much of a delay I still continue to get the same error message. I have pulled the Filing Download API quick-start.ipynb notebook from the docs, and still run in to this issue with any of the links I try. However, if I use the placeholder example  link for exhibit_99_url in that notebook ("https://www.sec.gov/ix?doc=/Archives/edgar/data/1320695/000132069520000148/ths12-31x201910krecast.htm"), I get an expected response with a 200.

A few EX-99 links I am attempting to download: https://www.sec.gov/Archives/edgar/data/1128361/000112836124000034/hopeq32024ccdeck.htm, https://www.sec.gov/Archives/edgar/data/46195/000095017024117652/boh-ex99_2.htm
https://www.sec.gov/Archives/edgar/data/1468174/000119312524244755/d851972dex991.htm

I initially attempt to generate the pdf when the 8K is first received from the realtime websocket. Would understand a delay there since it is a new filing, but even 6+ hours later the 202 remains. Additionally, I saw this [previous issue](https://github.com/janlukasschroeder/sec-api/issues/30) about leading 0's in the URL. Wondering if it could be similar?

The way I am retrieving these URLs: from an 8K, I loop through the documentFormatFiles and if contains "EX" I use the documentUrl. Pretty much identical to your [example](https://sec-api.io/docs/sec-filings-render-api/python-example#download-press-releases-in-exhibit-99-from-8-k-filings).

Would appreciate any insight to dealing with this. I do not mind pulling these EX-99 PDFs at a later time, I am just unsure how long they need to process and my current retry logic window is obviously too short.

Thanks, 
Lilly

**Comment by janlukasschroeder** [comment]
@lilly-lumosity Thanks for bringing this to our attention, much appreciated and very helpful. We experienced a temporary queue overflow in one of our PDF generator systems the caused a constant flow of 202 responses. The issue has been resolved and you should be able to get PDFs as usual. I also tested your URLs, and all of them are working now. 

Thanks again for your support!

**Comment by lilly-lumosity** [comment]
Thank you for the quick response and fix!
