### ISSUE TITLE
Search API does not support application/json content type in request

### ISSUE THREAD

**Issue by volgin** [janlukasschroeder/sec-api#6]
Since the API expects a JSON object in a POST request, it's worth noting in the documentation that the request should _not_ have its content type set to "application/json". It took me some time to figure out because the API simply responds with empty results.

Ideally, the API should support "application/json" content type as well. Or, at least, respond with an error when the wrong content-type is set on the request.

**Comment by janlukasschroeder** [comment]
@volgin The API supports application/json. Post the payload to https://api.sec-api.io and you'll see the matching results.

```json
{
    "query": {
        "query_string": {
            "query": "cik:320193 AND filedAt:{2016-01-01 TO 2016-12-31} AND formType:\"10-Q\""
        }
    },
    "from": "0",
    "size": "10",
    "sort": [
        {
            "filedAt": {
                "order": "desc"
            }
        }
    ]
}
```

Corresponding curl:

```bash
curl -XPOST -H "Content-type: application/json" -d '{
    "query": {
        "query_string": {
            "query": "cik:320193 AND filedAt:{2016-01-01 TO 2016-12-31} AND formType:\"10-Q\""
        }
    },
    "from": "0",
    "size": "10",
    "sort": [
        {
            "filedAt": {
                "order": "desc"
            }
        }
    ]
}' 'https://api.sec-api.io'
```

**Comment by volgin** [comment]
The problem is that CIK:320193 works, but CIK:0000320193 does not. And 0000320193 is the real CIK.
That was threw me off, because CIK:0000320193 returns empty.

**Comment by volgin** [comment]
Note also that the results have an empty "ticker" property.

**Comment by janlukasschroeder** [comment]
> The problem is that CIK:320193 works, but CIK:0000320193 does not. And 0000320193 is the real CIK.

Correct. I'll make this clear in the documentation. Either trailing `0` need to be removed before sending it to the API or

**Comment by janlukasschroeder** [comment]
> Note also that the results have an empty "ticker" property.

Yeah, some company tickers are still indexed.
