### ISSUE TITLE
Wrong search results

### ISSUE THREAD

**Issue by volgin** [janlukasschroeder/sec-api#7]
The following request:

`curl -d '{"query":{"query_string":{"query":"cik:0000320193 AND formType:\"10-Q\""}},"from":"0","size":"10","sort":[{"filedAt":{"order":"desc"}}]}' -X POST https://api.sec-api.io`

returns results completely unrelated to the query.

**Comment by volgin** [comment]
The example request from the Medium article also returns results unrelated to the query:

'{"query": {"query_string": {"query": "cik:320193 AND filedAt:{2016-01-01 TO 2016-12-31} AND formType:\"10-Q\""}}, "from": "0", "size": "10", "sort": [{"filedAt": {"order": "desc"}}]}'

'''
{"took":27,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":6289104,"max_score":1,"hits":[{"_index":"filings","_type":"_doc","_id":"e542a0834ad9c986474e78c24bc0f605","_score":1,"_source":{"cik":"1028734","ticker":"","companyName":"COBIZ FINANCIAL INC","formType":"4","filedAt":"2018-10-03","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028734/0001028734-18-000132.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028734/0001028734-18-000132-index.htm","id":"e542a0834ad9c986474e78c24bc0f605"}},{"_index":"filings","_type":"_doc","_id":"4d40d9a2f63b74baefee96dd7edc9af1","_score":1,"_source":{"cik":"1028734","ticker":"","companyName":"COBIZ FINANCIAL INC","formType":"4","filedAt":"2018-10-03","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028734/0001739385-18-000002.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028734/0001739385-18-000002-index.htm","id":"4d40d9a2f63b74baefee96dd7edc9af1"}},{"_index":"filings","_type":"_doc","_id":"4f6aa680a00024b5954451a42c1e8fb4","_score":1,"_source":{"cik":"1028734","ticker":"","companyName":"COBIZ FINANCIAL INC","formType":"8-K","filedAt":"2018-10-01","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028734/0001028734-18-000117.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028734/0001028734-18-000117-index.htm","id":"4f6aa680a00024b5954451a42c1e8fb4"}},{"_index":"filings","_type":"_doc","_id":"8a74dc7b06f646c22476af25d3fba012","_score":1,"_source":{"cik":"1028734","ticker":"","companyName":"COBIZ FINANCIAL INC","formType":"S-8 POS","filedAt":"2018-10-01","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028734/0001104659-18-059751.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028734/0001104659-18-059751-index.htm","id":"8a74dc7b06f646c22476af25d3fba012"}},{"_index":"filings","_type":"_doc","_id":"45df24d125c8c7c045d4060ba8e9e796","_score":1,"_source":{"cik":"1028734","ticker":"","companyName":"COBIZ FINANCIAL INC","formType":"S-8 POS","filedAt":"2018-10-01","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028734/0001104659-18-059753.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028734/0001104659-18-059753-index.htm","id":"45df24d125c8c7c045d4060ba8e9e796"}},{"_index":"filings","_type":"_doc","_id":"ad70cf1a1ddc91aceb94868e81d3caf5","_score":1,"_source":{"cik":"1028734","ticker":"","companyName":"COBIZ FINANCIAL INC","formType":"SC 13G/A","filedAt":"2018-10-10","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028734/0000215457-18-006095.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028734/0000215457-18-006095-index.htm","id":"ad70cf1a1ddc91aceb94868e81d3caf5"}},{"_index":"filings","_type":"_doc","_id":"b796a526e62ddaf7012a8a20ed3a944c","_score":1,"_source":{"cik":"1028817","ticker":"","companyName":"CINE GUARANTORS II INC","formType":"UPLOAD","filedAt":"2018-10-04","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028817/0000000000-18-031269.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028817/0000000000-18-031269-index.htm","id":"b796a526e62ddaf7012a8a20ed3a944c"}},{"_index":"filings","_type":"_doc","_id":"6ba80390616a6133fdd9daba38f5bbdb","_score":1,"_source":{"cik":"1028918","ticker":"","companyName":"PACIFIC PREMIER BANCORP INC","formType":"4","filedAt":"2018-10-03","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028918/0001028918-18-000189.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028918/0001028918-18-000189-index.htm","id":"6ba80390616a6133fdd9daba38f5bbdb"}},{"_index":"filings","_type":"_doc","_id":"816fd4e631e1f7d97675e649fcbbf376","_score":1,"_source":{"cik":"1028918","ticker":"","companyName":"PACIFIC PREMIER BANCORP INC","formType":"4","filedAt":"2018-12-06","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028918/0001028918-18-000215.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028918/0001028918-18-000215-index.htm","id":"816fd4e631e1f7d97675e649fcbbf376"}},{"_index":"filings","_type":"_doc","_id":"7534a48e58e933f13b67c07ba3f075db","_score":1,"_source":{"cik":"1028918","ticker":"","companyName":"PACIFIC PREMIER BANCORP INC","formType":"8-K","filedAt":"2018-11-08","linkToTxt":"https://www.sec.gov/Archives/edgar/data/1028918/0001028918-18-000206.txt","linkToHtml":"https://www.sec.gov/Archives/edgar/data/1028918/0001028918-18-000206-index.htm","id":"7534a48e58e933f13b67c07ba3f075db"}}]}}
'''

**Comment by janlukasschroeder** [comment]
Try

```bash
curl -XPOST -H "Content-type: application/json" -d '{
    "query": {
        "query_string": {
            "query": "cik:320193 AND filedAt:{2016-01-01 TO 2016-12-31} AND formType:\"10-Q\""
        }
    },
    "from": "0",
    "size": "10",
    "sort": [
        {
            "filedAt": {
                "order": "desc"
            }
        }
    ]
}' 'https://api.sec-api.io'
```

**Comment by volgin** [comment]
See #6 .
