### ISSUE TITLE
Doesn't query any filings after Sept 11th 2019

### ISSUE THREAD

**Issue by atnickallen** [janlukasschroeder/sec-api#8]
Doesn't query any filings after Sept 11th 2019

**Comment by atnickallen** [comment]
**The following query returns 0 results:**

{
"query": {
"query_string": {
"query": "filedAt:{2019-09-12 TO 2019-09-15}"
}
},
"from": "0",
"size": "9999",
"sort": [
{
"filedAt": {
"order": "desc"
}
}
]
}

**Comment by janlukasschroeder** [comment]
@atnickallen the bug fix is live now
